# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o902DHbvHTnJEhrEhwS-ok0_tEz3AT6
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Fungsi untuk menggambar segitiga
def draw_triangle(a, b):
    c = round((a**2 + b**2)**0.5, 2)
    fig, ax = plt.subplots()
    ax.plot([0, a, 0, 0], [0, 0, b, 0], color='blue')
    ax.fill([0, a, 0], [0, 0, b], 'skyblue', alpha=0.4)
    ax.text(a / 2, -1, f"a = {a}", ha='center')
    ax.text(-1, b / 2, f"b = {b}", va='center', rotation='vertical')
    ax.text(a / 2.5, b / 2.5, f"c = {c}", fontsize=12, color='red')
    ax.set_xlim(-2, max(10, a+2))
    ax.set_ylim(-2, max(10, b+2))
    ax.set_aspect('equal')
    ax.set_title("Visualisasi Segitiga Pythagoras")
    return fig, c

# Sidebar navigasi
st.sidebar.title("Menu Laboratorium")
menu = st.sidebar.radio("Menu Laporatorium ini terdiri dari:", ["TUJUAN PEMBELAJARAN", "PETUNJUK PENGGUNAAN", "JELAJAH TEOREMA PYTHAGORAS"])

if menu == "TUJUAN PEMBELAJARAN":
    st.markdown("""
        <style>
        /* Background keseluruhan aplikasi */
        .stApp {
            background-color: #FAF3E0; /* pastel cream */
            padding: 2rem;
        }

        /* Judul */
        .judul {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 32px;
            font-weight: bold;
            color: #577590; /* soft bluish grey */
            background-color: #F6D6AD; /* peach pastel */
            padding: 12px 24px;
            border-radius: 15px;
            display: inline-block;
            box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 25px;
        }

        /* Konten teks */
        .isi {
            font-family: 'Segoe UI', sans-serif;
            font-size: 18px;
            color: #444444;
            background-color: #DFF5F2; /* pastel mint */
            padding: 18px;
            border-radius: 12px;
            line-height: 1.75;
            box-shadow: 1px 1px 5px rgba(0,0,0,0.05);
        }

        ul {
            margin-top: 10px;
        }

        li {
            margin-bottom: 10px;
        }
        </style>
    """, unsafe_allow_html=True)

    st.markdown("<div class='judul'> Tujuan Pembelajaran</div>", unsafe_allow_html=True)

    st.markdown("""
        <div class='isi'>
        Setelah menggunakan laboratorium ini, diharapkan dapat:
        <ul>
            <li>Menemukan rumus Pythagoras melalui visualisasi segitiga siku-siku secara konkret</li>
            <li>Memahami dan menjelaskan keterkaitan antara panjang sisi-sisi segitiga tersebut</li>
        </ul>
        </div>
    """, unsafe_allow_html=True)
# Halaman 2: Petunjuk
elif menu == "PETUNJUK PENGGUNAAN":
    st.title("Petunjuk Penjelajahan Pythagenius")
    st.markdown("""
<div style="text-align: justify; font-size: 16px;">
Untuk memulai penjelajahan teorema Pythagoras menggunakan aplikasi <strong>Pythagenius</strong>, ikuti langkah-langkah berikut:

1. Buka menu <strong>Jelajah Teorema Pythagoras</strong> yang tersedia di sisi kiri layar atau bagian atas aplikasi.  
2. Gunakan <em>slider</em> untuk memilih panjang dua sisi siku-siku, yaitu sisi <code>a</code> dan sisi <code>b</code>. Silakan geser sesuai angka yang diinginkan. Pilihan ini akan membentuk segitiga siku-siku secara otomatis.  
3. Amati perubahan visual segitiga yang ditampilkan di layar. Aplikasi akan menampilkan bentuk segitiga lengkap dengan panjang sisi <code>a</code>, <code>b</code>, dan <code>c</code>, serta sudut siku-sikunya.  
4. Nilai sisi miring <code>c</code> (hipotenusa) akan dihitung dan ditampilkan secara otomatis berdasarkan input yang diberikan. Proses ini menunjukkan bagaimana teorema Pythagoras bekerja secara langsung.  
5. Lakukan pengulangan dengan memilih nilai yang berbeda untuk <code>a</code> dan <code>b</code>, agar kamu bisa melihat pola yang terbentuk dan memahami hubungan antar sisi dalam berbagai kondisi segitiga.

<br>
Melalui langkah-langkah ini, kamu dapat mempelajari dan menemukan sendiri bagaimana teorema Pythagoras bekerja.
</div>
""", unsafe_allow_html=True)


# Halaman 3: Eksperimen
elif menu == "JELAJAH TEOREMA PYTHAGORAS":
    st.title("Jelajah Teorema Pythagoras")
    st.write("Atur panjang sisi siku-siku dan lihat bagaimana sisi miring dihitung dan divisualisasikan.")

    a = st.slider("Panjang sisi a (horizontal)", 1, 20, 5)
    b = st.slider("Panjang sisi b (vertikal)", 1, 20, 5)

    fig, c = draw_triangle(a, b)
    st.pyplot(fig)
