# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o902DHbvHTnJEhrEhwS-ok0_tEz3AT6
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Fungsi untuk menggambar segitiga
def draw_triangle(a, b):
    c = round((a**2 + b**2)**0.5, 2)
    fig, ax = plt.subplots()
    ax.plot([0, a, 0, 0], [0, 0, b, 0], color='blue')
    ax.fill([0, a, 0], [0, 0, b], 'skyblue', alpha=0.4)
    ax.text(a / 2, -1, f"a = {a}", ha='center')
    ax.text(-1, b / 2, f"b = {b}", va='center', rotation='vertical')
    ax.text(a / 2.5, b / 2.5, f"c = {c}", fontsize=12, color='red')
    ax.set_xlim(-2, max(10, a+2))
    ax.set_ylim(-2, max(10, b+2))
    ax.set_aspect('equal')
    ax.set_title("Visualisasi Segitiga Pythagoras")
    return fig, c

# Sidebar navigasi
st.sidebar.title("Menu Laboratorium")
menu = st.sidebar.radio("Pilih Halaman", ["Tujuan Pembelajaran", "Cara Memakai", "Eksperimen Pythagoras"])

if menu == "Tujuan Pembelajaran":
    st.markdown("""
        <style>
        /* Ubah font dan ukuran judul */
        .judul {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 32px;
            font-weight: bold;
            color: #4B8BBE;
            margin-bottom: 10px;
        }

        /* Ubah font dan ukuran isi */
        .isi {
            font-family: 'Verdana', sans-serif;
            font-size: 18px;
            color: #333333;
            line-height: 1.6;
        }
        </style>
    """, unsafe_allow_html=True)

    st.markdown("<div class='judul'>🎯 Tujuan Pembelajaran</div>", unsafe_allow_html=True)

    st.markdown("""
        <div class='isi'>
        Setelah menggunakan laboratorium ini, diharapkan dapat:
        <ul>
            <li>Menemukan rumus Pythagoras melalui visualisasi segitiga siku-siku secara konkret</li>
            <li>Memahami dan menjelaskan keterkaitan antara panjang sisi-sisi segitiga tersebut</li>
        </ul>
        </div>
    """, unsafe_allow_html=True)
# Halaman 2: Cara Memakai
elif menu == "Cara Memakai":
    st.title("🛠️ Cara Memakai Laboratorium")
    st.write("""
    1. Masuk ke menu **Eksperimen Pythagoras**
    2. Gunakan **slider** untuk memilih panjang sisi `a` dan `b`
    3. Lihat hasil visualisasi segitiga siku-siku di layar
    4. Perhatikan nilai sisi miring `c` yang dihitung otomatis
    5. Ulangi dengan nilai berbeda untuk eksperimen lainnya
    """)

# Halaman 3: Eksperimen
elif menu == "Eksperimen Pythagoras":
    st.title("🧪 Eksperimen Segitiga Pythagoras")
    st.write("Atur panjang sisi siku-siku dan lihat bagaimana sisi miring dihitung dan divisualisasikan.")

    a = st.slider("Panjang sisi a (horizontal)", 1, 20, 5)
    b = st.slider("Panjang sisi b (vertikal)", 1, 20, 5)

    fig, c = draw_triangle(a, b)
    st.pyplot(fig)
