# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o902DHbvHTnJEhrEhwS-ok0_tEz3AT6
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np


def draw_triangle(a, b):
    c = round((a**2 + b**2)**0.5, 2)
    fig, ax = plt.subplots()

    # Titik-titik segitiga
    A = (0, 0)
    B = (a, 0)
    C = (0, b)

    # Gambar segitiga
    ax.plot([A[0], B[0], C[0], A[0]], [A[1], B[1], C[1], A[1]], color='#3B3B98', linewidth=2.5)
    ax.fill([A[0], B[0], C[0]], [A[1], B[1], C[1]], '#74b9ff', alpha=0.4)

    # Ukuran font dinamis (1/5 panjang sisi)
    font_a = max(8, a * 0.2)
    font_b = max(8, b * 0.2)
    font_c = max(8, c * 0.2)

    # Label sisi a (AB)
    mid_ab = ((A[0] + B[0]) / 2, (A[1] + B[1]) / 2)
    ax.text(mid_ab[0], mid_ab[1] - 0.5, f"a = {a}", ha='center', va='top', fontsize=font_a, color='#2d3436')

    # Label sisi b (AC)
    mid_ac = ((A[0] + C[0]) / 2, (A[1] + C[1]) / 2)
    ax.text(mid_ac[0] - 0.5, mid_ac[1], f"b = {b}", ha='right', va='center', fontsize=font_b, color='#2d3436')

    # Label sisi c (BC) - di luar sisi, tidak menempel
    mid_bc = ((B[0] + C[0]) / 2, (B[1] + C[1]) / 2)
    dx = C[0] - B[0]
    dy = C[1] - B[1]
    norm = (dx**2 + dy**2)**0.5
    offset = max(2, c * 0.2)  # offset diperbesar biar jelas keluar

    # Vektor tegak lurus ke sisi BC yang mengarah ke LUAR segitiga
    # Kita asumsikan segitiga siku-siku di A (0,0), jadi arah keluar bisa pakai (+dy, -dx)
    offset_x = dy / norm * offset
    offset_y = -dx / norm * offset

    ax.text(mid_bc[0] + offset_x, mid_bc[1] + offset_y, f"c = {c}",
            ha='center', va='center', fontsize=font_c, color='red')


    # Sumbu tetap dari 0-20
    ax.set_xlim(-5, 20)
    ax.set_ylim(-5, 20)
    ax.set_aspect('equal')
    ax.set_title("Visualisasi Segitiga")
    ax.grid(True)
    ax.set_xlabel("alas")
    ax.set_ylabel("tinggi")

    return fig, c


# Custom global styling
st.markdown("""
    <style>
    html, body, [class*="css"] {
        font-family: 'Segoe UI', sans-serif;
    }

    .stApp {
        background-color: #FAF3E0;
        color: #2d3436;
    }

    .css-1d391kg {  /* style for sidebar */
        background-color: #f8e1d4;
    }

    .css-1v0mbdj, .css-1cpxqw2, .st-c1, .st-bk {
        font-family: 'Segoe UI', sans-serif !important;
    }

    h1, h2, h3, h4 {
        color: #3B3B98;
        font-family: 'Trebuchet MS', sans-serif;
    }

    .stSlider > div[data-baseweb="slider"] > div {
        background-color: #3B3B98;
    }

    .stSlider > div[data-baseweb="slider"] > div > div {
        background-color: #F6D6AD;
    }
    </style>
""", unsafe_allow_html=True)

# Sidebar navigasi
st.sidebar.title("JELAJAH TEOREMA PYTHAGORAS")
menu = st.sidebar.radio("MENU",["Beranda", "Petunjuk Penggunaan", "Eksperimen Pythagoras"])

if menu == "Beranda":
    st.markdown("""
        <style>
        .judul {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 32px;
            font-weight: bold;
            color: #3B3B98;
            background-color: #F6D6AD;
            padding: 12px 24px;
            border-radius: 15px;
            display: inline-block;
            box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 25px;
        }

        .isi {
            font-family: 'Segoe UI', sans-serif;
            font-size: 18px;
            color: #444444;
            background-color: #DFF5F2;
            padding: 18px;
            border-radius: 12px;
            line-height: 1.75;
            box-shadow: 1px 1px 5px rgba(0,0,0,0.05);
        }

        ul {
            margin-top: 10px;
        }

        li {
            margin-bottom: 10px;
        }
        </style>
    """, unsafe_allow_html=True)

    st.markdown("<div class='judul'> JELAJAH TEOREMA PYTHAGORAS</div>", unsafe_allow_html=True)

    st.markdown("""
        <div class='isi'>
    <p><strong>Pythagenius</strong> adalah aplikasi interaktif yang dirancang untuk membantu kamu menjelajahi dan memahami Teorema Pythagoras secara menyenangkan. Dengan bantuan visualisasi segitiga, kamu bisa melihat langsung bagaimana hubungan antar sisi bekerja dan menemukan rumusnya secara intuitif.</p>
    Setelah menggunakan laboratorium ini, siswa diharapkan mampu:
    <ul>
        <li>Menemukan rumus Pythagoras melalui visualisasi segitiga siku-siku secara konkret</li>
        <li>Memahami dan menjelaskan keterkaitan antara panjang sisi-sisi segitiga tersebut</li>
    </ul>
    </div>
    """, unsafe_allow_html=True)

# Halaman 2: Petunjuk
elif menu == "Petunjuk Penggunaan":
    st.markdown("""
        <style>
        .judul-petunjuk {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 30px;
            font-weight: bold;
            color: #3B3B98;
            background-color: #F6D6AD;
            padding: 12px 24px;
            border-radius: 15px;
            display: inline-block;
            box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }

        .isi-petunjuk {
            font-family: 'Segoe UI', sans-serif;
            font-size: 16px;
            text-align: justify;
            color: #2d3436;
            background-color: #DFF5F2;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 1px 1px 4px rgba(0,0,0,0.05);
            line-height: 1.8;
        }

        .isi-petunjuk code {
            background-color: #ffeaa7;
            padding: 2px 4px;
            border-radius: 4px;
            font-size: 15px;
        }

        .isi-petunjuk em {
            color: #6c5ce7;
            font-style: normal;
            font-weight: 600;
        }

        .isi-petunjuk strong {
            color: #3B3B98;
        }
        </style>
    """, unsafe_allow_html=True)

    st.markdown("<div class='judul-petunjuk'>PETUNJUK PENJELAJAHAN PYTHAGORAS", unsafe_allow_html=True)

    st.markdown("""
        <div class='isi-petunjuk'>
        Untuk memulai penjelajahan teorema Pythagoras menggunakan aplikasi <strong>Pythagenius</strong>, ikuti langkah-langkah berikut:

        <ol>
            <li>Buka menu <strong>Jelajah Teorema Pythagoras</strong> yang tersedia di sisi kiri layar atau bagian atas aplikasi.</li>
            <li>Gunakan <em>slider</em> untuk memilih panjang dua sisi siku-siku, yaitu sisi <code>a</code> dan sisi <code>b</code>. Silakan geser sesuai angka yang diinginkan.</li>
            <li>Amati perubahan visual segitiga yang ditampilkan di layar. Aplikasi akan menampilkan bentuk segitiga lengkap dengan panjang sisi <code>a</code>, <code>b</code>, dan <code>c</code>, serta sudut siku-sikunya.</li>
            <li>Nilai sisi miring <code>c</code> (hipotenusa) akan dihitung dan ditampilkan secara otomatis berdasarkan input yang diberikan. Proses ini menunjukkan bagaimana teorema Pythagoras bekerja secara langsung.</li>
            <li>Lakukan pengulangan dengan memilih nilai yang berbeda untuk <code>a</code> dan <code>b</code>, agar kamu bisa melihat pola yang terbentuk dan memahami hubungan antar sisi dalam berbagai kondisi segitiga.</li>
        </ol>

        Dengan mengikuti langkah-langkah di atas, kamu dapat mempelajari dan menemukan sendiri bagaimana teorema Pythagoras bekerja secara menyenangkan!
        </div>
    """, unsafe_allow_html=True)


# Halaman 3: Eksperimen
elif menu == "Eksperimen Pythagoras":
    st.markdown("""
    <style>
    .stApp {
        background-color: #FFF6E0;
    }
    .judul-experimen {
        font-family: 'Trebuchet MS', sans-serif;
        font-size: 30px;
        font-weight: bold;
        color: #3B3B98;
        background-color: #F6D6AD;
        padding: 12px 24px;
        border-radius: 15px;
        display: inline-block;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
        margin-bottom: 20px;
    }
    .subjudul {
        font-size: 17px;
        color: #636e72;
        margin-bottom: 1.5em;
    }
    .stSlider > div[data-baseweb="slider"] > div {
        background-color: #DFF5F2;
        height: 6px;
        border-radius: 8px;
    }
    div[role="slider"] {
        background-color: #3B3B98 !important;
        border: 2px solid #dfe6e9;
        height: 20px;
        width: 20px;
        margin-top: -7px;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("<div class='judul-experimen'>JELAJAH TEOREMA PYTHAGORAS</div>", unsafe_allow_html=True)
    st.markdown("<div class='subjudul'>Atur panjang sisi siku-siku dan lihat bagaimana sisi miring dihitung dan divisualisasikan.</div>", unsafe_allow_html=True)

    a = st.slider("Panjang sisi a (alas)", 1, 20, 5)
    b = st.slider("Panjang sisi b (tinggi)", 1, 20, 5)

    fig, c = draw_triangle(a, b)
    st.pyplot(fig)
