# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oPo3utVVi-R2TgZrc3xaGxGDZLIDFat
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import Polygon, Rectangle

# Konfigurasi halaman
st.set_page_config(
    page_title="Penemuan Pythagoras",
    page_icon="🔺",
    layout="centered"
)

# CSS kustom untuk tampilan menarik
st.markdown("""
<style>
    .main {
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    }
    .stSlider>div>div>div>div {
        background: #4b6cb7 !important;
    }
    .st-bb {
        background-color: #ffffff;
    }
    .st-at {
        background-color: #4b6cb7;
    }
    .st-ax {
        background-color: #4b6cb7;
    }
    div[data-baseweb="select"]>div {
        border-color: #4b6cb7 !important;
    }
</style>
""", unsafe_allow_html=True)

# Header aplikasi
st.title("🔍 Penemuan Teorema Pythagoras")
st.markdown("""
**Eksplorasi interaktif hubungan antara sisi-sisi segitiga siku-siku**
Ubah panjang sisi dan amati hubungan matematis yang muncul!
""")

# Kontainer utama
with st.container():
    col1, col2 = st.columns([1, 2])

    with col1:
        # Input interaktif
        st.subheader("Atur Panjang Sisi")
        a = st.slider("Sisi tegak (a)", 1.0, 10.0, 3.0, 0.1)
        b = st.slider("Sisi datar (b)", 1.0, 10.0, 4.0, 0.1)

        # Hitungan Pythagoras
        c = np.sqrt(a**2 + b**2)
        a_sq = a**2
        b_sq = b**2
        c_sq = c**2

        st.markdown(f"""
        **Hasil Perhitungan:**
        - a² = {a}² = {a_sq:.2f}
        - b² = {b}² = {b_sq:.2f}
        - c² = {c:.2f}² = {c_sq:.2f}
        """)

        # Mode pencarian sisi
        st.subheader("Cari Sisi yang Hilang")
        mode = st.radio(
            "Pilih mode:",
            ["Hitung sisi miring (c)", "Hitung sisi lain"],
            index=0
        )

        if mode == "Hitung sisi lain":
            known = st.selectbox("Sisi yang diketahui", ["a & c", "b & c"])
            if known == "a & c":
                a_input = st.number_input("Masukkan a", min_value=1.0, value=3.0)
                c_input = st.number_input("Masukkan c", min_value=1.0, value=5.0)
                if c_input > a_input:
                    b_result = np.sqrt(c_input**2 - a_input**2)
                    st.success(f"Panjang sisi b = {b_result:.2f}")
            else:
                b_input = st.number_input("Masukkan b", min_value=1.0, value=4.0)
                c_input = st.number_input("Masukkan c", min_value=1.0, value=5.0)
                if c_input > b_input:
                    a_result = np.sqrt(c_input**2 - b_input**2)
                    st.success(f"Panjang sisi a = {a_result:.2f}")

    with col2:
        # Visualisasi segitiga
        st.subheader("Visualisasi Segitiga")
        fig, ax = plt.subplots(figsize=(6, 6))

        # Gambar segitiga
        triangle = Polygon([[0, 0], [a, 0], [0, b]], closed=True,
                          fill=True, color='skyblue', alpha=0.6)
        ax.add_patch(triangle)

        # Gambar sudut siku-siku
        rect = Rectangle((0, 0), min(a,b)/5, min(a,b)/5,
                        fill=True, color='red', alpha=0.5)
        ax.add_patch(rect)

        # Label sisi
        ax.text(a/2, -0.3, f'a = {a}', ha='center', fontsize=10)
        ax.text(-0.3, b/2, f'b = {b}', va='center', fontsize=10)
        ax.text(a/3, b/3, f'c = {c:.2f}',
               rotation=np.degrees(np.arctan(b/a)),
               ha='center', va='center', fontsize=10)

        # Label sudut
        ax.text(0.1, 0.1, '90°', fontsize=8)
        ax.text(a-0.2, 0.2, f'{np.degrees(np.arctan(b/a)):.1f}°', fontsize=8)
        ax.text(0.2, b-0.2, f'{90-np.degrees(np.arctan(b/a)):.1f}°', fontsize=8)

        ax.set_xlim(-0.5, a+0.5)
        ax.set_ylim(-0.5, b+0.5)
        ax.set_aspect('equal')
        ax.axis('off')
        st.pyplot(fig)

# Bagian eksplorasi
st.markdown("---")
st.subheader("🔎 Eksplorasi Matematis")
st.markdown("""
Coba lengkapi tabel berikut dan amati polanya:
""")

# Buat tabel eksplorasi
data = {
    "a": [3, 5, 6, a],
    "b": [4, 12, 8, b],
    "a²": [9, 25, 36, a_sq],
    "b²": [16, 144, 64, b_sq],
    "a² + b²": [25, 169, 100, a_sq + b_sq],
    "c (hitung)": [5, 13, 10, c],
    "c²": [25, 169, 100, c_sq]
}

# Tambahkan data input user ke tabel
df = pd.DataFrame(data)
st.dataframe(df.style.highlight_max(axis=0, color='#fffd75'),
             use_container_width=True)

# Pertanyaan pemandu
st.markdown("""
**Pertanyaan Eksplorasi:**
1. Apa hubungan antara nilai di kolom 'a² + b²' dan 'c²'?
2. Apa yang terjadi jika kamu mengubah panjang sisi a atau b?
3. Bisakah kamu menemukan pola matematisnya?
""")

# Catatan kaki
st.markdown("---")
st.caption("Aplikasi Pembelajaran Interaktif © 2023 | Gunakan eksplorasi untuk menemukan teorema Pythagoras sendiri!")
